---
language: node_js
node_js:
  - "0.12"
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g grunt-cli"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install
script:
  - npm test

branches:
  only:
    - master

matrix:
  fast_finish: true
